POST http://localhost:9990/signup
Content-Type: application/json

{
    "employeetype":"node",
    "name":"node",
    "email":"node@gmail.com",
    "contactnumber":"9505209762",
    "password" : "node",
    "confirmpassword" : "node"
}


###

POST http://localhost:9999/login
Content-Type: application/json

{
    "email" : "react@gmail.com",
    "password" : "react"
}